version: '2'
services:
    iresearch-app:
        image: iresearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://iresearch-mysql:3306/iresearch?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    iresearch-mysql:
        extends:
            file: mysql.yml
            service: iresearch-mysql
